@startuml
node Backend as backend <<device>>{

}

node Compute as compute <<device>>{

}
node "Data fetcher" as crawler <<device>>

cloud "Local network"  as local_network{

}

cloud cloud as _cloud

database Database as db <<device>>{
    artifact postgres {
        artifact Article
        artifact Proccessed
        artifact Topic
        artifact User
        artifact Task
        artifact TaskProccessed
        artifact YouTubeConfig
        artifact YouTubeSearch
    }
}



backend --> local_network: TCP/IP
compute --> local_network: TCP/IP
crawler --> local_network: TCP/IP

node "Flutter app" as app <<device>> {

}

node "Web server" as appweb <<device>>

node "Smartphone/Computer" as smartdevice <<device>>

actor User as user

user --> app
user --> smartdevice
app --> _cloud: TCP/IP
smartdevice-->_cloud: TCP/IP
local_network --> _cloud: TCP/IP
appweb --> local_network: TCP/IP
appweb --> _cloud: TCP/IP
db --> local_network: TCP/IP

@enduml

